### PR TITLE
Fix countable issues for php 7.2 compatibility

### LINKED ISSUE #35: Fix PHP 7.2 compatibility issue with "countable"
Customer reported this error:

```
Warning: count(): Parameter must be an array or an object that implements Countable in wp-content/plugins/organize-series/orgSeries-template-tags.php on line 489.
```

Customer recently moved to a new host and I suspect this is from their new site running on PHP 7.2.

### PR DESCRIPTION
**Pull request by nerrad**
Fixes #35 

## Testing:

* [x] Anything using `get_series_list` and series counts etc in the list table.
* [x] orgseries feed on settings page.
* [x] anything using `set_series_order` (just test that automatic ordering still works as expected).
* [x] anything using `set_post_series` (so assigning a post to a series)
* [x] verify display of series information for a post is correct
* [x] verify series meta strip displays correctly
* [x] verify series nav strip displays correctly
* [x] verify seriestoc widget works correctly and displays custom widget title okay

### CODE REVIEW

File: orgSeries-taxonomy.php [hunk 1]
```diff
@@ -119,7 +119,7 @@ function set_series_order($postid = 0, $series_part = 0, $series_id, $is_publish
  	$series_posts = get_series_order($post_ids_in_series, $postid, $series_id, true, false);
 	$parts_array = array();
 
-	$total_posts = count( $series_posts ) + 1;
+	$total_posts = is_array($series_posts) ? count( $series_posts ) + 1 : 1;
```
Comment (nerrad) [inline orgSeries-taxonomy.php]: This seems odd that we're adding a count here.  But I'm preserving existing behaviour (hence the default of 1 when not an array).
